### ISSUE TITLE
App won't launch with package

### ISSUE THREAD

**Issue by Meghatronics** [zahniar88/simple_markdown_editor#1]
See error here. 
![image](https://user-images.githubusercontent.com/53065184/131187776-b3b6d22f-7b32-4d8e-8bbf-0762403bb296.png)

/C:/Users/LENOVO/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/simple_markdown_editor-0.1.3/lib/src/z_markdown_editor.dart:129:21: Error: No named parameter with the name 'scrollController'.
                    scrollController: widget.scrollController,
                    ^^^^^^^^^^^^^^^^
/C:/Users/LENOVO/fvm/versions/stable/packages/flutter/lib/src/material/text_form_field.dart:135:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({

  ^^^^^^^^^^^^^

**Comment by zahniar88** [comment]
> See error here.
> ![image](https://user-images.githubusercontent.com/53065184/131187776-b3b6d22f-7b32-4d8e-8bbf-0762403bb296.png)
> 
> /C:/Users/LENOVO/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/simple_markdown_editor-0.1.3/lib/src/z_markdown_editor.dart:129:21: Error: No named parameter with the name 'scrollController'.
> scrollController: widget.scrollController,
> ^^^^^^^^^^^^^^^^
> /C:/Users/LENOVO/fvm/versions/stable/packages/flutter/lib/src/material/text_form_field.dart:135:3: Context: Found this candidate, but the arguments don't match.
> TextFormField({
> 
> ^^^^^^^^^^^^^

@Meghatronics 
I will find the error and I will fix it in the next update.  May I know what version of Flutter are you using?

**Comment by zahniar88** [comment]
> See error here.
> ![image](https://user-images.githubusercontent.com/53065184/131187776-b3b6d22f-7b32-4d8e-8bbf-0762403bb296.png)
> 
> /C:/Users/LENOVO/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/simple_markdown_editor-0.1.3/lib/src/z_markdown_editor.dart:129:21: Error: No named parameter with the name 'scrollController'.
> scrollController: widget.scrollController,
> ^^^^^^^^^^^^^^^^
> /C:/Users/LENOVO/fvm/versions/stable/packages/flutter/lib/src/material/text_form_field.dart:135:3: Context: Found this candidate, but the arguments don't match.
> TextFormField({
> 
> ^^^^^^^^^^^^^

@Meghatronics 
I think the flutter version you are using is outdated.  try upgrading to version 2.2.x.  I will close this issue
