### ISSUE TITLE
The control disposes textcontroller that is passed in

### ISSUE THREAD

**Issue by jdr1** [zahniar88/simple_markdown_editor#2]
I came across an issue I think is a bug, The control currently disposes of the textController that is passed in constructor but I believe it should only do this if it was responsible for creating it.

There are situations where the text controller will still be needed if a parent widget creates but is not showing the markdown control (eg a tab view).

**Comment by zahniar88** [comment]
Give me time to fix it. I'm working on another project. I need more time to find and fixed this bug.
