### ISSUE TITLE
an exception was thrown when popping back to the previous page route

### ISSUE THREAD

**Issue by Void-7** [zahniar88/simple_markdown_editor#3]
ERROR HINTS are as follow:

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
#1      ChangeNotifier._debugAssertNotDisposed
#2      ChangeNotifier.dispose
#3      _MarkdownFormFieldState.dispose
#4      StatefulElement.unmount
...
════════════════════════════════════════════════════════════════════════════════
D/MIUIInput(13321): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=383632633, downTime=383632633, deviceId=-1, source=0x101, displayId=0 }
D/MIUIInput(13321): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=383632633, downTime=383632633, deviceId=-1, source=0x101, displayId=0 }

════════ Exception caught by widgets library ═══════════════════════════════════
A TextEditingController was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

**Comment by Void-7** [comment]
the thing is when I came back from EDITING PAGE to the previous page, it would threw an exception. Really don know why. Please help.  thx!

**Comment by Void-7** [comment]
`import 'package:flutter/material.dart';
import 'package:simple_markdown_editor/simple_markdown_editor.dart';
import 'package:bot_toast/bot_toast.dart';

class PostPage extends StatefulWidget {
  final arguments;
  PostPage({this.arguments});

  @override
  _PostPage createState() {
    return _PostPage(arguments: this.arguments);
  }
}

class _PostPage extends State<PostPage> {
  final arguments;
  TextEditingController _title_controller = TextEditingController();
  TextEditingController _controller = TextEditingController();
  FocusNode _focusNode = FocusNode();

  String errorHintText;
  _PostPage({this.arguments});

  @override
  void dispose() {
    _controller.dispose();
    _title_controller.dispose();
    _focusNode.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    this._title_controller.addListener(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        extendBodyBehindAppBar: true,
        appBar: AppBar(
          leading: IconButton(
              icon: Icon(Icons.arrow_back_ios_new),
              onPressed: () {
                Navigator.of(context).pop();
              }),
          title: Text('EDIT POST'),
          centerTitle: true,
          actions: [
            TextButton(
                style: ButtonStyle(
                    overlayColor:
                        MaterialStateProperty.all(Colors.transparent)),
                onPressed: () {
                  if (_title_controller.text.isEmpty ||
                      _controller.text.isEmpty) {
                    var a = getTextToast('PLEASE FILL THE TITLE OR POST CONTENT~',
                        ctcol: Colors.red, col: Colors.white);
                  } else {
                    var b = getTextToast('COMPLETED！',
                        ctcol: Colors.green, col: Colors.white);
                  }
                },
                child: Text('发布',
                    style: TextStyle(color: Colors.white, fontSize: 16)))
          ],
        ),
        body: Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('images/bg.jpg'),
                fit: BoxFit.cover,
              ),
            ),
            child: MediaQuery.removePadding(
                context: context,
                removeTop: true,
                child: ListView(
                  children: [
                    Container(
                      margin: EdgeInsets.fromLTRB(25, 110, 25, 30),
                      padding: EdgeInsets.all(0.0),
                      decoration: BoxDecoration(
                          boxShadow: [
                            BoxShadow(
                                color: Colors.grey.withOpacity(0.10),
                                offset: Offset(3.9, 5.0), 
                                blurRadius: 6, 
                                spreadRadius: 1 
                                )
                          ],
                          color: Color.fromRGBO(255, 255, 255, 0.90),
                          borderRadius: BorderRadius.all(Radius.circular(30))),
                      child: Container(
                          width: double.infinity,
                          padding: EdgeInsets.all(10),
                          child: Center(
                              child: TextField(
                            textAlign: TextAlign.center,
                            controller: _title_controller,
                            maxLines: 1,
                            maxLength: 32,
                            onChanged: (text) {
                              setState(() {
                                if (text.length == 32) {
                                  var cancel = getTextToast('MAX 32 ~',
                                      align: Alignment.topCenter,
                                      ctcol: Colors.white);
                                  cancel();
                                }
                              });
                            },
                            decoration: InputDecoration(
                              suffixIcon: Offstage(
                                  offstage: _title_controller.text.isEmpty,
                                  child: IconButton(
                                    onPressed: () {
                                      _title_controller.clear();
                                      setState(() {
                                        //防止按下清除按钮后仍然显示
                                        _title_controller.text =
                                            _title_controller.text;
                                      });
                                    },
                                    icon: Icon(
                                      Icons.clear,
                                      color: Colors.black54,
                                      size: 20,
                                    ),
                                  )),
                              counterText: '',
                              border: InputBorder.none,
                              hintText: 'INPUT TITLE HERE',
                            ),
                          ))),
                    ),
                    Container(
                      margin: EdgeInsets.fromLTRB(25, 0, 25, 0),
                      height: 600,
                      decoration: BoxDecoration(
                          boxShadow: [
                            BoxShadow(
                                color: Colors.grey.withOpacity(0.10),
                                offset: Offset(3.9, 5.0),
                                blurRadius: 6, 
                                spreadRadius: 1 
                                )
                          ],
                          color: Color.fromRGBO(255, 255, 255, 0.90),
                          borderRadius: BorderRadius.all(Radius.circular(30))),
                      padding: EdgeInsets.all(15),
                      child: MarkdownFormField(
                        controller: _controller,
                        enableToolBar: true,
                        emojiConvert: true,
                        autoCloseAfterSelectEmoji: false,
                      ),
                    )
                  ],
                )))
        );
  }
}

getTextToast(String content,
    {double radius = 15,
    Color col = Colors.black54,
    FontWeight fw = FontWeight.bold,
    Color ctcol = Colors.white70,
    AlignmentGeometry align = Alignment.center}) {
  return BotToast.showText(
      text: content,
      borderRadius: BorderRadius.all(Radius.circular(radius)),
      textStyle: TextStyle(color: col, fontWeight: fw),
      contentColor: ctcol,
      align: align);
}
`

**Comment by zahniar88** [comment]
Ok, I'll try to fix it. Give me time. Thx

**Comment by Void-7** [comment]
```Dart

import 'package:flutter/material.dart';
import 'package:simple_markdown_editor/simple_markdown_editor.dart';
import 'package:bot_toast/bot_toast.dart';

class PostPage extends StatefulWidget {
  final arguments;
  PostPage({this.arguments});

  @override
  _PostPage createState() {
    return _PostPage(arguments: this.arguments);
  }
}

class _PostPage extends State<PostPage> {
  final arguments;
  TextEditingController _title_controller = TextEditingController();
  TextEditingController _controller = TextEditingController();
  FocusNode _focusNode = FocusNode();

  String errorHintText;
  _PostPage({this.arguments});

  @override
  void dispose() {
    _controller.dispose();
    _title_controller.dispose();
    _focusNode.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    this._title_controller.addListener(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        extendBodyBehindAppBar: true,
        appBar: AppBar(
          leading: IconButton(
              icon: Icon(Icons.arrow_back_ios_new),
              onPressed: () {
                Navigator.of(context).pop();
              }),
          title: Text('EDIT'),
          centerTitle: true,
          actions: [
            TextButton(
                style: ButtonStyle(
                    overlayColor:
                        MaterialStateProperty.all(Colors.transparent)),
                onPressed: () {
                },
                child: Text('PUBLISH',
                    style: TextStyle(color: Colors.white, fontSize: 16)))
          ],
        ),
        body: Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('images/bg.jpg'),
                fit: BoxFit.cover,
              ),
            ),
            child: MediaQuery.removePadding(
                context: context,
                removeTop: true,
                child: ListView(
                  children: [
                    Container(
                      margin: EdgeInsets.fromLTRB(25, 110, 25, 30),
                      padding: EdgeInsets.all(0.0),
                      decoration: BoxDecoration(
                          boxShadow: [
                            BoxShadow(
                                color: Colors.grey.withOpacity(0.10),
                                offset: Offset(3.9, 5.0), 
                                blurRadius: 6, 
                                spreadRadius: 1 
                                )
                          ],
                          color: Color.fromRGBO(255, 255, 255, 0.90),
                          borderRadius: BorderRadius.all(Radius.circular(30))),
                      child: Container(
                          width: double.infinity,
                          padding: EdgeInsets.all(10),
                          child: Center(
                              child: TextField(
                            textAlign: TextAlign.center,
                            controller: _title_controller,
                            maxLines: 1,
                            maxLength: 32,
                            onChanged: (text) {
                              setState(() {
                               
                                }
                              });
                            },
                            decoration: InputDecoration(
                              suffixIcon: Offstage(
                                  offstage: _title_controller.text.isEmpty,
                                  child: IconButton(
                                    onPressed: () {
                                      _title_controller.clear();
                                      setState(() {
                                        _title_controller.text =
                                            _title_controller.text;
                                      });
                                    },
                                    icon: Icon(
                                      Icons.clear,
                                      color: Colors.black54,
                                      size: 20,
                                    ),
                                  )),
                              counterText: '',
                              border: InputBorder.none,
                              hintText: 'INPUT TITLE',
                            ),
                          ))),
                    ),
                    Container(
                      margin: EdgeInsets.fromLTRB(25, 0, 25, 0),
                      height: 600,
                      decoration: BoxDecoration(
                          boxShadow: [
                            BoxShadow(
                                color: Colors.grey.withOpacity(0.10),
                                offset: Offset(3.9, 5.0), 
                                blurRadius: 6, 
                                spreadRadius: 1
                                )
                          ],
                          color: Color.fromRGBO(255, 255, 255, 0.90),
                          borderRadius: BorderRadius.all(Radius.circular(30))),
                      padding: EdgeInsets.all(15),
                      child: MarkdownFormField(
                        controller: _controller,
                        enableToolBar: true,
                        emojiConvert: true,
                        autoCloseAfterSelectEmoji: false,
                      ),
                    )
                  ],
                )))
        );
  }
}

getTextToast(String content,
    {double radius = 15,
    Color col = Colors.black54,
    FontWeight fw = FontWeight.bold,
    Color ctcol = Colors.white70,
    AlignmentGeometry align = Alignment.center}) {
  return BotToast.showText(
      text: content,
      borderRadius: BorderRadius.all(Radius.circular(radius)),
      textStyle: TextStyle(color: col, fontWeight: fw),
      contentColor: ctcol,
      align: align);
}


```

**Comment by Void-7** [comment]
> 
> 
> Ok, I'll try to fix it. Give me time. Thx

thx 4 ur help!  My codes r as above if it may give a help

**Comment by dinukakulatunga** [comment]
> the thing is when I came back from EDITING PAGE to the previous page, it would threw an exception. Really don know why. Please help. thx!

I'm having the same issue.

**Comment by dinukakulatunga** [comment]
I have added two markdown widgets inside my form, but when I submit my form same exception showing
